name: gimnasio_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.1.2

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  mask_text_input_formatter: ^2.5.0
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  dio: ^5.4.3
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/fondo.png
